package com.huaisun.graduation.auto.mapper;

import com.huaisun.graduation.auto.dao.TDetailOrder;
import com.huaisun.graduation.auto.dao.TDetailOrderExample;
import com.huaisun.graduation.auto.dao.TDetailOrderKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDetailOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail_order
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    long countByExample(TDetailOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail_order
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    int deleteByExample(TDetailOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail_order
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    int deleteByPrimaryKey(TDetailOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail_order
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    int insert(TDetailOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail_order
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    int insertSelective(TDetailOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail_order
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    List<TDetailOrder> selectByExample(TDetailOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail_order
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    TDetailOrder selectByPrimaryKey(TDetailOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail_order
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") TDetailOrder record, @Param("example") TDetailOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail_order
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    int updateByExample(@Param("record") TDetailOrder record, @Param("example") TDetailOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail_order
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    int updateByPrimaryKeySelective(TDetailOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail_order
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    int updateByPrimaryKey(TDetailOrder record);
}