package com.huaisun.graduation.auto.mapper;

import com.huaisun.graduation.auto.dao.TEmploy;
import com.huaisun.graduation.auto.dao.TEmployExample;
import com.huaisun.graduation.auto.dao.TEmployKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TEmployMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOY
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    long countByExample(TEmployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOY
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    int deleteByExample(TEmployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOY
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    int deleteByPrimaryKey(TEmployKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOY
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    int insert(TEmploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOY
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    int insertSelective(TEmploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOY
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    List<TEmploy> selectByExample(TEmployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOY
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    TEmploy selectByPrimaryKey(TEmployKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOY
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") TEmploy record, @Param("example") TEmployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOY
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    int updateByExample(@Param("record") TEmploy record, @Param("example") TEmployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOY
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    int updateByPrimaryKeySelective(TEmploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOY
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    int updateByPrimaryKey(TEmploy record);
}