package com.huaisun.graduation.auto.mapper;

import com.huaisun.graduation.auto.dao.TMilkMenu;
import com.huaisun.graduation.auto.dao.TMilkMenuExample;
import com.huaisun.graduation.auto.dao.TMilkMenuKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMilkMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_milk_menu
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    long countByExample(TMilkMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_milk_menu
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    int deleteByExample(TMilkMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_milk_menu
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    int deleteByPrimaryKey(TMilkMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_milk_menu
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    int insert(TMilkMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_milk_menu
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    int insertSelective(TMilkMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_milk_menu
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    List<TMilkMenu> selectByExample(TMilkMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_milk_menu
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    TMilkMenu selectByPrimaryKey(TMilkMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_milk_menu
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") TMilkMenu record, @Param("example") TMilkMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_milk_menu
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    int updateByExample(@Param("record") TMilkMenu record, @Param("example") TMilkMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_milk_menu
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    int updateByPrimaryKeySelective(TMilkMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_milk_menu
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    int updateByPrimaryKey(TMilkMenu record);
}