package com.huaisun.graduation.auto.dao;

public class TCartKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.m_id
     *
     * @mbg.generated Fri Apr 19 23:21:32 CST 2019
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.kind
     *
     * @mbg.generated Fri Apr 19 23:21:32 CST 2019
     */
    private String kind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.m_id
     *
     * @return the value of t_cart.m_id
     *
     * @mbg.generated Fri Apr 19 23:21:32 CST 2019
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.m_id
     *
     * @param mId the value for t_cart.m_id
     *
     * @mbg.generated Fri Apr 19 23:21:32 CST 2019
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.kind
     *
     * @return the value of t_cart.kind
     *
     * @mbg.generated Fri Apr 19 23:21:32 CST 2019
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.kind
     *
     * @param kind the value for t_cart.kind
     *
     * @mbg.generated Fri Apr 19 23:21:32 CST 2019
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }
}