package com.huaisun.graduation.auto.dao;

public class TCartKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.m_id
     *
     * @mbg.generated Wed Apr 10 20:13:24 CST 2019
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.u_id
     *
     * @mbg.generated Wed Apr 10 20:13:24 CST 2019
     */
    private Integer uId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.m_id
     *
     * @return the value of t_cart.m_id
     *
     * @mbg.generated Wed Apr 10 20:13:24 CST 2019
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.m_id
     *
     * @param mId the value for t_cart.m_id
     *
     * @mbg.generated Wed Apr 10 20:13:24 CST 2019
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.u_id
     *
     * @return the value of t_cart.u_id
     *
     * @mbg.generated Wed Apr 10 20:13:24 CST 2019
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.u_id
     *
     * @param uId the value for t_cart.u_id
     *
     * @mbg.generated Wed Apr 10 20:13:24 CST 2019
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }
}