package com.huaisun.graduation.auto.dao;

public class TCart extends TCartKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.number
     *
     * @mbg.generated Wed Apr 10 20:13:24 CST 2019
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.number
     *
     * @return the value of t_cart.number
     *
     * @mbg.generated Wed Apr 10 20:13:24 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.number
     *
     * @param number the value for t_cart.number
     *
     * @mbg.generated Wed Apr 10 20:13:24 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}