package com.huaisun.graduation.auto.dao;

public class TDetailOrder extends TDetailOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_detail_order.number
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_detail_order.number
     *
     * @return the value of t_detail_order.number
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_detail_order.number
     *
     * @param number the value for t_detail_order.number
     *
     * @mbg.generated Sun Apr 21 15:09:34 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}