package com.huaisun.graduation.auto.dao;

import java.util.Date;

public class TEmploy extends TEmployKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOY.NAME
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOY.PHONE
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOY.EMAIL
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOY.PASSWORD
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOY.ADDRESS
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOY.HEAD
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    private String head;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOY.CREATE_DATE
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMPLOY.VALID
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    private String valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOY.NAME
     *
     * @return the value of T_EMPLOY.NAME
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOY.NAME
     *
     * @param name the value for T_EMPLOY.NAME
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOY.PHONE
     *
     * @return the value of T_EMPLOY.PHONE
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOY.PHONE
     *
     * @param phone the value for T_EMPLOY.PHONE
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOY.EMAIL
     *
     * @return the value of T_EMPLOY.EMAIL
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOY.EMAIL
     *
     * @param email the value for T_EMPLOY.EMAIL
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOY.PASSWORD
     *
     * @return the value of T_EMPLOY.PASSWORD
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOY.PASSWORD
     *
     * @param password the value for T_EMPLOY.PASSWORD
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOY.ADDRESS
     *
     * @return the value of T_EMPLOY.ADDRESS
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOY.ADDRESS
     *
     * @param address the value for T_EMPLOY.ADDRESS
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOY.HEAD
     *
     * @return the value of T_EMPLOY.HEAD
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOY.HEAD
     *
     * @param head the value for T_EMPLOY.HEAD
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public void setHead(String head) {
        this.head = head == null ? null : head.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOY.CREATE_DATE
     *
     * @return the value of T_EMPLOY.CREATE_DATE
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOY.CREATE_DATE
     *
     * @param createDate the value for T_EMPLOY.CREATE_DATE
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMPLOY.VALID
     *
     * @return the value of T_EMPLOY.VALID
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMPLOY.VALID
     *
     * @param valid the value for T_EMPLOY.VALID
     *
     * @mbg.generated Mon Feb 25 13:25:44 CST 2019
     */
    public void setValid(String valid) {
        this.valid = valid == null ? null : valid.trim();
    }
}