package com.huaisun.graduation.auto.dao;

import java.util.Date;

public class TEmploy extends TEmployKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employ.name
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employ.phone
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employ.email
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employ.password
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employ.address
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employ.head
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private String head;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employ.create_date
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employ.valid
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employ.name
     *
     * @return the value of t_employ.name
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employ.name
     *
     * @param name the value for t_employ.name
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employ.phone
     *
     * @return the value of t_employ.phone
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employ.phone
     *
     * @param phone the value for t_employ.phone
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employ.email
     *
     * @return the value of t_employ.email
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employ.email
     *
     * @param email the value for t_employ.email
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employ.password
     *
     * @return the value of t_employ.password
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employ.password
     *
     * @param password the value for t_employ.password
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employ.address
     *
     * @return the value of t_employ.address
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employ.address
     *
     * @param address the value for t_employ.address
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employ.head
     *
     * @return the value of t_employ.head
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employ.head
     *
     * @param head the value for t_employ.head
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setHead(String head) {
        this.head = head == null ? null : head.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employ.create_date
     *
     * @return the value of t_employ.create_date
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employ.create_date
     *
     * @param createDate the value for t_employ.create_date
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employ.valid
     *
     * @return the value of t_employ.valid
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employ.valid
     *
     * @param valid the value for t_employ.valid
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}