package com.huaisun.graduation.auto.dao;

import java.math.BigDecimal;

public class TMilkMenu extends TMilkMenuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_milk_menu.milk_name
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    private String milkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_milk_menu.milk_detail
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    private String milkDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_milk_menu.milk_grade
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    private Integer milkGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_milk_menu.milk_price
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    private BigDecimal milkPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_milk_menu.milk_photo
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    private String milkPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_milk_menu.shelf
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    private Integer shelf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_milk_menu.milk_name
     *
     * @return the value of t_milk_menu.milk_name
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public String getMilkName() {
        return milkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_milk_menu.milk_name
     *
     * @param milkName the value for t_milk_menu.milk_name
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public void setMilkName(String milkName) {
        this.milkName = milkName == null ? null : milkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_milk_menu.milk_detail
     *
     * @return the value of t_milk_menu.milk_detail
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public String getMilkDetail() {
        return milkDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_milk_menu.milk_detail
     *
     * @param milkDetail the value for t_milk_menu.milk_detail
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public void setMilkDetail(String milkDetail) {
        this.milkDetail = milkDetail == null ? null : milkDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_milk_menu.milk_grade
     *
     * @return the value of t_milk_menu.milk_grade
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public Integer getMilkGrade() {
        return milkGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_milk_menu.milk_grade
     *
     * @param milkGrade the value for t_milk_menu.milk_grade
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public void setMilkGrade(Integer milkGrade) {
        this.milkGrade = milkGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_milk_menu.milk_price
     *
     * @return the value of t_milk_menu.milk_price
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public BigDecimal getMilkPrice() {
        return milkPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_milk_menu.milk_price
     *
     * @param milkPrice the value for t_milk_menu.milk_price
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public void setMilkPrice(BigDecimal milkPrice) {
        this.milkPrice = milkPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_milk_menu.milk_photo
     *
     * @return the value of t_milk_menu.milk_photo
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public String getMilkPhoto() {
        return milkPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_milk_menu.milk_photo
     *
     * @param milkPhoto the value for t_milk_menu.milk_photo
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public void setMilkPhoto(String milkPhoto) {
        this.milkPhoto = milkPhoto == null ? null : milkPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_milk_menu.shelf
     *
     * @return the value of t_milk_menu.shelf
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public Integer getShelf() {
        return shelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_milk_menu.shelf
     *
     * @param shelf the value for t_milk_menu.shelf
     *
     * @mbg.generated Mon Apr 15 19:37:27 CST 2019
     */
    public void setShelf(Integer shelf) {
        this.shelf = shelf;
    }
}