package com.huaisun.graduation.auto.dao;

import java.math.BigDecimal;

public class TMilkMenu extends TMilkMenuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_milk_menu.milk_name
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    private String milkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_milk_menu.milk_price
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    private BigDecimal milkPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_milk_menu.milk_address
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    private String milkAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_milk_menu.is_shelf
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    private Integer isShelf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_milk_menu.milk_name
     *
     * @return the value of t_milk_menu.milk_name
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    public String getMilkName() {
        return milkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_milk_menu.milk_name
     *
     * @param milkName the value for t_milk_menu.milk_name
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    public void setMilkName(String milkName) {
        this.milkName = milkName == null ? null : milkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_milk_menu.milk_price
     *
     * @return the value of t_milk_menu.milk_price
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    public BigDecimal getMilkPrice() {
        return milkPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_milk_menu.milk_price
     *
     * @param milkPrice the value for t_milk_menu.milk_price
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    public void setMilkPrice(BigDecimal milkPrice) {
        this.milkPrice = milkPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_milk_menu.milk_address
     *
     * @return the value of t_milk_menu.milk_address
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    public String getMilkAddress() {
        return milkAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_milk_menu.milk_address
     *
     * @param milkAddress the value for t_milk_menu.milk_address
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    public void setMilkAddress(String milkAddress) {
        this.milkAddress = milkAddress == null ? null : milkAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_milk_menu.is_shelf
     *
     * @return the value of t_milk_menu.is_shelf
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    public Integer getIsShelf() {
        return isShelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_milk_menu.is_shelf
     *
     * @param isShelf the value for t_milk_menu.is_shelf
     *
     * @mbg.generated Fri Mar 22 09:43:02 CST 2019
     */
    public void setIsShelf(Integer isShelf) {
        this.isShelf = isShelf;
    }
}