package com.huaisun.graduation.auto.dao;

import java.math.BigDecimal;
import java.util.Date;

public class TOrder extends TOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.u_id
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_date
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.mode
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private String mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.valid
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.price
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.count
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.cost
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private BigDecimal cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.payment
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    private String payment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.u_id
     *
     * @return the value of t_order.u_id
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.u_id
     *
     * @param uId the value for t_order.u_id
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_date
     *
     * @return the value of t_order.create_date
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_date
     *
     * @param createDate the value for t_order.create_date
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.mode
     *
     * @return the value of t_order.mode
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.mode
     *
     * @param mode the value for t_order.mode
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.valid
     *
     * @return the value of t_order.valid
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.valid
     *
     * @param valid the value for t_order.valid
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.price
     *
     * @return the value of t_order.price
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.price
     *
     * @param price the value for t_order.price
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.count
     *
     * @return the value of t_order.count
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.count
     *
     * @param count the value for t_order.count
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.cost
     *
     * @return the value of t_order.cost
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.cost
     *
     * @param cost the value for t_order.cost
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.payment
     *
     * @return the value of t_order.payment
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.payment
     *
     * @param payment the value for t_order.payment
     *
     * @mbg.generated Thu Mar 28 18:16:25 CST 2019
     */
    public void setPayment(String payment) {
        this.payment = payment == null ? null : payment.trim();
    }
}