package com.huaisun.graduation.auto.dao;

public class TOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ID
     *
     * @mbg.generated Mon Mar 04 13:15:49 CST 2019
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ID
     *
     * @return the value of t_order.ID
     *
     * @mbg.generated Mon Mar 04 13:15:49 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ID
     *
     * @param id the value for t_order.ID
     *
     * @mbg.generated Mon Mar 04 13:15:49 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}