package com.huaisun.graduation.auto.dao;

import java.math.BigDecimal;
import java.util.Date;

public class TOrder extends TOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.U_ID
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.CREATE
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    private Date create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.MODE
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    private String mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.VALID
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    private String valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.PRICE
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.COST
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    private BigDecimal cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.PROFIT
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    private BigDecimal profit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.U_ID
     *
     * @return the value of T_ORDER.U_ID
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.U_ID
     *
     * @param uId the value for T_ORDER.U_ID
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.CREATE
     *
     * @return the value of T_ORDER.CREATE
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public Date getCreate() {
        return create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.CREATE
     *
     * @param create the value for T_ORDER.CREATE
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public void setCreate(Date create) {
        this.create = create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.MODE
     *
     * @return the value of T_ORDER.MODE
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.MODE
     *
     * @param mode the value for T_ORDER.MODE
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.VALID
     *
     * @return the value of T_ORDER.VALID
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.VALID
     *
     * @param valid the value for T_ORDER.VALID
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public void setValid(String valid) {
        this.valid = valid == null ? null : valid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.PRICE
     *
     * @return the value of T_ORDER.PRICE
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.PRICE
     *
     * @param price the value for T_ORDER.PRICE
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.COST
     *
     * @return the value of T_ORDER.COST
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.COST
     *
     * @param cost the value for T_ORDER.COST
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.PROFIT
     *
     * @return the value of T_ORDER.PROFIT
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.PROFIT
     *
     * @param profit the value for T_ORDER.PROFIT
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }
}