package com.huaisun.graduation.auto.dao;

public class TOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ID
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ID
     *
     * @return the value of T_ORDER.ID
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ID
     *
     * @param id the value for T_ORDER.ID
     *
     * @mbg.generated Mon Feb 25 13:28:08 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}