package com.huaisun.graduation.auto.dao;

import java.math.BigDecimal;

public class TSpecifications extends TSpecificationsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_specifications.name
     *
     * @mbg.generated Mon Apr 15 19:35:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_specifications.price
     *
     * @mbg.generated Mon Apr 15 19:35:07 CST 2019
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_specifications.name
     *
     * @return the value of t_specifications.name
     *
     * @mbg.generated Mon Apr 15 19:35:07 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_specifications.name
     *
     * @param name the value for t_specifications.name
     *
     * @mbg.generated Mon Apr 15 19:35:07 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_specifications.price
     *
     * @return the value of t_specifications.price
     *
     * @mbg.generated Mon Apr 15 19:35:07 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_specifications.price
     *
     * @param price the value for t_specifications.price
     *
     * @mbg.generated Mon Apr 15 19:35:07 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}