package com.huaisun.graduation.auto.dao;

public class TSpecificationsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_specifications.id
     *
     * @mbg.generated Mon Apr 15 19:35:07 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_specifications.id
     *
     * @return the value of t_specifications.id
     *
     * @mbg.generated Mon Apr 15 19:35:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_specifications.id
     *
     * @param id the value for t_specifications.id
     *
     * @mbg.generated Mon Apr 15 19:35:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}