package com.huaisun.graduation.auto.dao;

public class TUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.ID
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.ID
     *
     * @return the value of T_USER.ID
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.ID
     *
     * @param id the value for T_USER.ID
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}