package com.huaisun.graduation.auto.dao;

import java.util.Date;

public class TUser extends TUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.NAME
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.EMAIL
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.PHONE
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.INTEGRAL
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.BALANCE
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    private Float balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.COST
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    private Float cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.CREATE_DATE
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.NAME
     *
     * @return the value of T_USER.NAME
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.NAME
     *
     * @param name the value for T_USER.NAME
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.EMAIL
     *
     * @return the value of T_USER.EMAIL
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.EMAIL
     *
     * @param email the value for T_USER.EMAIL
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.PHONE
     *
     * @return the value of T_USER.PHONE
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.PHONE
     *
     * @param phone the value for T_USER.PHONE
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.INTEGRAL
     *
     * @return the value of T_USER.INTEGRAL
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.INTEGRAL
     *
     * @param integral the value for T_USER.INTEGRAL
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.BALANCE
     *
     * @return the value of T_USER.BALANCE
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public Float getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.BALANCE
     *
     * @param balance the value for T_USER.BALANCE
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public void setBalance(Float balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.COST
     *
     * @return the value of T_USER.COST
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public Float getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.COST
     *
     * @param cost the value for T_USER.COST
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public void setCost(Float cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.CREATE_DATE
     *
     * @return the value of T_USER.CREATE_DATE
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.CREATE_DATE
     *
     * @param createDate the value for T_USER.CREATE_DATE
     *
     * @mbg.generated Mon Feb 25 18:10:18 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}