server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  ################# view #################
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  ################ upload ################
  servlet:
    multipart:
      max-file-size: 2MB

  ################ datasource ############
  datasource:
    url: jdbc:mysql://134.175.89.83:3306/db_wei_xiao?useSSL=false&ullNamePatternMatchesAll=true&amp;serverTimezone=GMT%2b8?useUnicode=true&characterEncoding=utf8
    username: huaisun
    password: Xy971002
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.huaisun.graduation.auto.mapper: DEBUG
    com.huaisun.graduation.mapper: DEBUG

