server:
  port: 8023
  tomcat:
    uri-encoding: UTF-8

spring:
  ################# view #################
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  ################ upload ################
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  ################ datasource ############
  datasource:
    url: jdbc:mysql://134.175.89.83:3306/db_wei_xiao?useUnicode=true&useSSL=true&characterEncoding=utf8
    username: root
    password: Sun961017
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-idle: 10
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      time-between-eviction-runs-millis: 18800
      min-evictable-idle-time-millis: 18800

  ################ mybatis ##############
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.huaisun.graduation.auto.mapper: DEBUG
    com.huaisun.graduation.mapper: DEBUG

