server:
  port: 8023
  tomcat:
    uri-encoding: UTF-8

spring:
  ################# view #################
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  ################ datasource ############
  datasource:
    url: jdbc:mysql://localhost:3306/db_wei_xiao?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.huaisun.graduation.auto.mapper: DEBUG
    com.huaisun.graduation.mapper: DEBUG

